
version: '3'
services:
  web:
    build: .
    ports: ["5000:5000"]
    env_file: .env
    depends_on: [db]
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gynos
      POSTGRES_PASSWORD: gynos
      POSTGRES_DB: gynos
